CREATE TABLE EMPLOYEES
(COD_EMP INT NOT NULL PRIMARY KEY,
NAME VARCHAR(30) NOT NULL,
FUNCTION VARCHAR(30) NOT NULL,
WAGE FLOAT NOT NULL
);

INSERT INTO EMPLOYEES VALUES
(1, 'Mark', 'CEO',28000),
(2, 'Jacob','Software Engineer',8300);